name: story-generator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - sqlalchemy==2.0.23
    - python-dotenv==1.0.0
    - pydantic==2.5.0
    - pydantic-settings==2.1.0
    - google-generativeai==0.3.0
    - python-multipart==0.0.6